NSCLC: lung cancer
LUAD: lung adenocarcinoma
LUSC: lung squamous cell carcinoma
HNSCC: head and neck squamous cell carcinoma
BRCA: breast cancer
CRC: colorectal cancer
PDAC: pancreatic ductal adenocarcinoma
GBM: glioblastoma
